version: '3.8'

networks:
  ups_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.170.0.0/24

services:
  m1:
    image: ubuntu:latest
    container_name: M1
    networks:
      ups_net:
        ipv4_address: 192.170.0.10
    tty: true
    privileged: true
    ports:
      - "2376:2376" # Puerto para acceder al Docker dentro de M1
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind-certs:/certs
      - dind-certs-ca:/certs-client
      - /var/run/docker.sock:/var/run/docker.sock

  m2:
    image: ubuntu:latest
    container_name: M2
    networks:
      ups_net:
        ipv4_address: 192.170.0.11
    tty: true
    privileged: true
    ports:
      - "2377:2377" # Puerto para acceder al Docker dentro de M2
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind-certs:/certs
      - dind-certs-ca:/certs-client
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  dind-certs:
  dind-certs-ca:
